import {
  ArrowLeft,
  ArrowLeftToLine,
  ArrowRight,
  CircleArrowRight,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CornerDownLeft,
  Ellipsis,
  EllipsisVertical,
  ExternalLink,
  Home,
  House,
  LayoutDashboard,
  Menu,
  Navigation as NavigationIcon,
  PanelLeft,
  PanelLeftClose,
  PanelLeftOpen,
} from 'lucide-react';

export {
  ArrowLeft,
  ArrowLeftToLine,
  ArrowRight,
  CircleArrowRight,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CornerDownLeft,
  Ellipsis,
  EllipsisVertical,
  ExternalLink,
  Home,
  House,
  LayoutDashboard,
  Menu,
  NavigationIcon as Navigation,
  PanelLeft,
  PanelLeftClose,
  PanelLeftOpen,
};

export const NavigationIcons = {
  ArrowLeft,
  ArrowLeftToLine,
  ArrowRight,
  CircleArrowRight,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CornerDownLeft,
  Ellipsis,
  EllipsisVertical,
  ExternalLink,
  Home,
  House,
  LayoutDashboard,
  Menu,
  Navigation: NavigationIcon,
  PanelLeft,
  PanelLeftClose,
  PanelLeftOpen,
};
